#!/bin/bash
#═══════════════════════════════════════════════════════════════════════════════
# ENTERPRISE UNIVERSE - AUTO DAILY BACKUP
# Creates daily backups and pushes to GitHub
# Author: GTz Ecosystem / West Money OS
# Usage: ./auto-backup.sh or via cron
#═══════════════════════════════════════════════════════════════════════════════

set -e

# Configuration
REPO_DIR="/home/administrator/Enterprise-Universe"
BACKUP_DIR="$REPO_DIR/backup"
DATE=$(date +%Y-%m-%d)
TIME=$(date +%H-%M-%S)
DAILY_DIR="$BACKUP_DIR/daily/$DATE"

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${BLUE}"
echo "╔══════════════════════════════════════════════════════════════════════════════╗"
echo "║        ENTERPRISE UNIVERSE - AUTO DAILY BACKUP                               ║"
echo "║                       $(date '+%Y-%m-%d %H:%M:%S')                                    ║"
echo "╚══════════════════════════════════════════════════════════════════════════════╝"
echo -e "${NC}"

# Create daily backup directory
mkdir -p "$DAILY_DIR"
mkdir -p "$DAILY_DIR/automation"
mkdir -p "$DAILY_DIR/api"
mkdir -p "$DAILY_DIR/config"
mkdir -p "$DAILY_DIR/logs"

echo -e "${YELLOW}[1/5] Creating backup for $DATE...${NC}"

# Backup automation scripts
echo "  - Backing up automation scripts..."
cp -r "$REPO_DIR/automation/"*.js "$DAILY_DIR/automation/" 2>/dev/null || true

# Backup API files
echo "  - Backing up API files..."
cp -r "$REPO_DIR/api/"*.js "$DAILY_DIR/api/" 2>/dev/null || true

# Backup config files
echo "  - Backing up config files..."
cp "$REPO_DIR/"*.json "$DAILY_DIR/config/" 2>/dev/null || true
cp "$REPO_DIR/.env.example" "$DAILY_DIR/config/" 2>/dev/null || true

# Backup logs (last state)
echo "  - Backing up log snapshots..."
cp "$REPO_DIR/logs/"*.json "$DAILY_DIR/logs/" 2>/dev/null || true
cp "$REPO_DIR/logs/"*.log "$DAILY_DIR/logs/" 2>/dev/null || true

# Generate backup manifest
echo -e "${YELLOW}[2/5] Generating backup manifest...${NC}"
cat > "$DAILY_DIR/MANIFEST.md" << EOF
# Enterprise Universe Backup - $DATE

## Backup Info
- **Date:** $DATE
- **Time:** $TIME
- **Host:** $(hostname)
- **User:** $(whoami)

## Files Backed Up

### Automation Scripts
\`\`\`
$(ls -la "$DAILY_DIR/automation/" 2>/dev/null || echo "No files")
\`\`\`

### API Files
\`\`\`
$(ls -la "$DAILY_DIR/api/" 2>/dev/null || echo "No files")
\`\`\`

### Config Files
\`\`\`
$(ls -la "$DAILY_DIR/config/" 2>/dev/null || echo "No files")
\`\`\`

### Log Snapshots
\`\`\`
$(ls -la "$DAILY_DIR/logs/" 2>/dev/null || echo "No files")
\`\`\`

## System Stats at Backup Time
- **Disk Usage:** $(df -h / | tail -1 | awk '{print $5}')
- **Memory:** $(free -h | grep Mem | awk '{print $3 "/" $2}')
- **Load:** $(uptime | awk -F'load average:' '{print $2}')

## Git Info
- **Branch:** $(cd "$REPO_DIR" && git branch --show-current)
- **Last Commit:** $(cd "$REPO_DIR" && git log -1 --oneline)

---
*Auto-generated by Enterprise Universe Backup System*
EOF

# Generate backup stats JSON
echo -e "${YELLOW}[3/5] Generating backup stats...${NC}"
cat > "$DAILY_DIR/backup-stats.json" << EOF
{
  "date": "$DATE",
  "time": "$TIME",
  "timestamp": "$(date -Iseconds)",
  "files": {
    "automation": $(ls -1 "$DAILY_DIR/automation/" 2>/dev/null | wc -l),
    "api": $(ls -1 "$DAILY_DIR/api/" 2>/dev/null | wc -l),
    "config": $(ls -1 "$DAILY_DIR/config/" 2>/dev/null | wc -l),
    "logs": $(ls -1 "$DAILY_DIR/logs/" 2>/dev/null | wc -l)
  },
  "totalSize": "$(du -sh "$DAILY_DIR" | cut -f1)",
  "gitBranch": "$(cd "$REPO_DIR" && git branch --show-current)",
  "gitCommit": "$(cd "$REPO_DIR" && git rev-parse --short HEAD)"
}
EOF

# Update backup index
echo -e "${YELLOW}[4/5] Updating backup index...${NC}"
cat > "$BACKUP_DIR/README.md" << EOF
# Enterprise Universe - Backup System

## Latest Backup
- **Date:** $DATE $TIME
- **Location:** \`backup/daily/$DATE/\`

## Backup Structure
\`\`\`
backup/
├── auto-backup.sh          # This backup script
├── README.md               # This file
└── daily/
    └── YYYY-MM-DD/         # Daily backup folders
        ├── MANIFEST.md     # Backup manifest
        ├── backup-stats.json
        ├── automation/     # Automation scripts
        ├── api/            # API files
        ├── config/         # Config files
        └── logs/           # Log snapshots
\`\`\`

## Available Backups
$(ls -1d "$BACKUP_DIR/daily/"*/ 2>/dev/null | while read dir; do
    date_dir=$(basename "$dir")
    size=$(du -sh "$dir" | cut -f1)
    echo "- **$date_dir** - Size: $size"
done || echo "No backups yet")

## Usage

### Manual Backup
\`\`\`bash
cd /home/administrator/Enterprise-Universe
./backup/auto-backup.sh
\`\`\`

### Setup Daily Cron (runs at 2:00 AM)
\`\`\`bash
crontab -e
# Add this line:
0 2 * * * /home/administrator/Enterprise-Universe/backup/auto-backup.sh >> /home/administrator/Enterprise-Universe/backup/cron.log 2>&1
\`\`\`

---
*Enterprise Universe Backup System - GTz Ecosystem*
EOF

# Git commit and push
echo -e "${YELLOW}[5/5] Pushing to GitHub...${NC}"
cd "$REPO_DIR"
git add backup/
git commit -m "Daily Backup: $DATE $TIME

- Automation scripts backup
- API files backup
- Config files backup
- Log snapshots

Co-Authored-By: Claude Opus 4.5 <noreply@anthropic.com>" || echo "No changes to commit"

git push origin main || echo "Push failed - check credentials"

echo ""
echo -e "${GREEN}╔══════════════════════════════════════════════════════════════════════════════╗"
echo "║                      BACKUP COMPLETED SUCCESSFULLY                           ║"
echo "╠══════════════════════════════════════════════════════════════════════════════╣"
echo "║  Location: backup/daily/$DATE/                                      ║"
echo "║  Size: $(du -sh "$DAILY_DIR" | cut -f1)                                                              ║"
echo "║  Files: $(find "$DAILY_DIR" -type f | wc -l) files backed up                                              ║"
echo "╚══════════════════════════════════════════════════════════════════════════════╝"
echo -e "${NC}"
